version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment: # connect the postgre sql 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" # port 
    volumes:
      - postgres_data:/var/lib/postgresql/data # save the all information 
    networks:
      - airflow_network 

networks:
  airflow_network:
    external: false

volumes:
  postgres_data: 